teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.5
      -
        axis: 0
        target: angular.z
        scale: 0.5

  laser_on:
    type: topic
    message_type: std_msgs/String
    topic_name: laser
    deadman_buttons: [5]
    message_value:
      -
        target: data
        value: 'on'

  laser_off:
    type: topic
    message_type: std_msgs/String
    topic_name: laser
    deadman_buttons: [7]
    message_value:
      -
        target: data
        value: 'off'
        